### ISSUE TITLE
What is the benefit of this over Lambada Scrapers ? 

### ISSUE THREAD

**Issue by SerpentDrago** [Dr-Know99/Global-Scrapers-Repo#1]
What Features does this have over the existing Lambada Scrapers project ? Does it offer better settings ? improved Scrapers ? 

Any reason not to just do fix's and PR's to Lambada Scrapers ? as its already running , active project with support from addons . 

[XKCD](https://imgs.xkcd.com/comics/standards.png)
comes to mind ....

Thanks !

**Comment by SerpentDrago** [comment]
[https://imgs.xkcd.com/comics/standards.png](url)

comes to mind ....

**Comment by drinfernoo** [comment]
My sentiments exactly.

**Comment by drchud** [comment]
> 
> 
> What Features does this have over the existing Lambada Scrapers project ? Does it offer better settings ? improved Scrapers ?
> 
> Any reason not to just do fix's and PR's to Lambada Scrapers ? as its already running , active project with support from addons .
> 
> [XKCD](https://imgs.xkcd.com/comics/standards.png)
> comes to mind ....
> 
> Thanks !

Wow im taking a screenshot of this shit cause u 2 homos look so despite lol. Why don't you leave people who have been in the scene doing their own thing way before you ALONE!?
Lets been honest here, why are u asking other people to contribute to ur loser project that is going no where fast???
Oh wait, you CAN'T CODE! You CANT WRITE OR FIX SCRAPERS!

Just give up losers, u suck fat fucking monkey balls!
Oh and weren't people from Jen and Universal telling ur dumb shits the same thing lol. Please contribute to UNIVERSAL SCRAPERS.

Another fact is we don't need more people like u (newbs) trying to make a module of the same fucking scrapers for all exodus forks.
And if u want that u got Universal with jen and Elysium forks.
My fork is different than redux cause i can write code, scrape other sites....not like u monkeys.
Just give up and go back to A4K. You guys don't bring shit to the table, learn to code fucks

**Comment by drinfernoo** [comment]
@drchud I feel like that got out of hand quickly, don't you? Especially considering this repo is basically a carbon copy of the early Lambda Scrapers repo, was made about two weeks after Lambda Scrapers came out, and is all hosted on a website built for hosting **open source code**, it's hard to tell where any of the code actually originated.

Just because you think you're the only one that can write a scraper, doesn't mean you've gotta be an ass about it.

**Comment by drchud** [comment]
> 
> 
> @drchud I feel like that got out of hand quickly, don't you? Especially considering this repo is basically a carbon copy of the early Lambda Scrapers repo, was made about two weeks after Lambda Scrapers came out, and is all hosted on a website built for hosting **open source code**, it's hard to tell where any of the code actually originated.
> 
> Just because you think you're the only one that can write a scraper, doesn't mean you've gotta be an ass about it.

I don't think its out of hand at all. Actually we need more people to stand up and say the truth.
Both of u no talent ass clowns are actually out of hand asking this guy to do fucking scraper work and pr's for ur lame module in which NONE of u even work on yourselves lol. <---Please read again so u fully understand! Maybe even a third time.

Lambda scrapers is old, outdated, broken shit and not even the creator of if can even submit a fix?? lol
Look at the pull requests sitting for weeks. Oh and having a little boy named jewbmx run around stealing scrapers doesn't count. Just as bad as eggman.

Its not my fault u didn't have to foresight to see this was a failed project from the beginning. Shit i realized when he made it, let it sit, no scraper fixes even though he said he knew how. Then out of the blue a clone of exodus appears and still no scraper fix's after months.
You guys got scammed lol.

Anyways, his repo is not a clone...not really sure what ur talking about. Looks like he probably got the idea for this global scrapers from iac sure. So what seems like he is just doing his own thing. And its seems a little different. But what the fuck do you think was going to happen lol.

IAC was the one who posted instructions on how to integrate a module into other forks on reddit. Which those same instructions are on other sites too. So u really cant been blaming this guy for running with it and doing his thing.

The reason im calling u out on ur shit, cause ur fucking bugging other people to do ur fucking work. There is no need for this shit. So get the fuck off your high horse, you're not special.

**Comment by SerpentDrago** [comment]
so apparently you can't have a normal conversation. have a good day. splitting up development only hurts the kodi scene.

**Comment by drchud** [comment]
> 
> 
> so apparently you can't have a normal conversation.
> 
> splitting up development only hurts the kodi scene.
> 
> my goal with this post wasn't to get in some dumb pissing contest. i was just wondering if good reason exists to split / fork / etc the work of getting one central exodus fork compatable scraper project.
> 
> You are absolutely more then welcome to contribute to whatever project you want.
> 
> have a good day.

Dude wtf don't u understand. I would being fucking retarded to have a normal conversation with u about this. 
If ur moron ass didnt notice this is for his addon Resistance. Which u should know its been around for some time, long before Redux and lambda scrapers. People like working on their own forks and projects.
AND NOT UR FAILED ADDON
